# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: smrabet <smrabet@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/11/06 16:47:14 by smrabet           #+#    #+#              #
#    Updated: 2015/11/06 16:47:30 by smrabet          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

GCCFLAGS = -Werror -Wall -Wextra

LIB = libft.a

all :
	gcc $(FLAGS) -o $(NAME) srcs/ft_putchar.c srcs/ft_putnbr.c srcs/ft_atoi.c srcs/add.c \
	srcs/mod.c srcs/div.c srcs/mul.c srcs/minus.c srcs/do_op.c

clean :
	rm -f $(NAME)

fclean : clean
